server {
    listen ${PORT};
    listen [::]:${PORT};
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Resolver para permitir variables en proxy_pass
    resolver 8.8.8.8 valid=30s;

    # Forzamos logs a la consola para ver qué pasa
    access_log /dev/stdout;
    error_log /dev/stdout debug;

    location /socket.io/ {
        set $signaling_url "${SIGNALING_URL}";
        if ($signaling_url = "") {
            return 404;
        }
        proxy_pass $signaling_url;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Assets estáticos
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
