worker_processes 1;
events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    # Logs a la consola de Railway
    access_log /dev/stdout;
    error_log /dev/stdout info;

    server {
        listen ${PORT};
        server_name _;
        root /usr/share/nginx/html;
        index index.html;
        
        resolver 8.8.8.8 valid=30s;

        location /socket.io/ {
            set $sig_url "${SIGNALING_URL}";
            if ($sig_url = "") { return 404; }
            
            proxy_pass $sig_url;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_cache_bypass 1;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }

        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }

        gzip on;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript image/svg+xml;
    }
}
