FROM php:8.2-fpm

# Instalar dependencias del sistema
RUN apt-get update && apt-get install -y 
    git 
    curl 
    libpng-dev 
    libonig-dev 
    libxml2-dev 
    zip 
    unzip 
    nodejs 
    npm


# Limpiar caché
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Instalar extensiones de PHP
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Obtener Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Configurar directorio de trabajo
WORKDIR /var/www

# Copiar el script de entrada y dar permisos
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# Copiar la configuración de PHP-FPM para que escuche en 0.0.0.0
COPY zz-docker.conf /etc/php/8.2/fpm/pool.d/zz-docker.conf


# Exponer el puerto para php-fpm
EXPOSE 9000

ENTRYPOINT ["entrypoint.sh"]